import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import Footer from "p/components/footer";
import HeaderNAvi from "p/components/header-navi";
import { getDictionary } from "p/get-dictionary";
import { Locale } from "p/i18-config";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: Locale };
})
{
  const dictionary = await getDictionary(lang);
  return (
    <html lang="en" className="relative imanity-text bg-noir">
      <body className="markerbysue-text">
      <div id="modal-root"></div>
       <HeaderNAvi navi={[dictionary["header"].navi[0], dictionary["header"].navi[1]]}  language= {dictionary["header"].language}></HeaderNAvi>
        {children}   
        <Footer></Footer>
       </body>
    </html>
  );
}